version: '2.2'

services:

  db:
    image: postgres:13.2
    shm_size: 1g
    ports:
      - "5444:5432"
    environment:
      # Obviously don't use this in production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
