[project]
name = "django_ltree_field"

[build-system]
requires = [
  "setuptools >= 45",
  "wheel",
  "setuptools_scm[toml]>=6.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "django_ltree_field/version.py"
local_scheme = "dirty-tag"
