# Generated by Django 3.1.7 on 2021-03-29 01:59

from django.db import migrations
import django.contrib.postgres.operations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        django.contrib.postgres.operations.CreateExtension(
            name='ltree',
        )
    ]
