# Generated by Django 3.1.7 on 2021-03-29 01:58

from django.db import migrations, models
import django_ltree_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django_ltree_field.fields.LTreeField()),
            ],
        ),
    ]
