# Generated by Django 3.1.7 on 2021-03-30 03:08

from django.db import migrations
import django_ltree_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20210330_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplenode',
            name='path',
            field=django_ltree_field.fields.LTreeField(db_index=True),
        ),
    ]
