# Generated by Django 5.1 on 2024-09-28 03:57

import django_ltree_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NullableNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", django_ltree_field.fields.LTreeField(null=True)),
            ],
            options={
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="SimpleNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", django_ltree_field.fields.LTreeField(db_index=True)),
            ],
            options={
                "ordering": ["path"],
            },
        ),
    ]
