# Generated by Django 5.1 on 2025-04-15 16:30

import django.contrib.postgres.indexes
import django_ltree_field.constants
import django_ltree_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NullableNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django_ltree_field.fields.LTreeField(null=True, triggers=django_ltree_field.constants.LTreeTrigger['CASCADE'], unique=True)),
            ],
            options={
                'ordering': ['path'],
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['path'], name='nullable_node_path_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProtectedNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django_ltree_field.fields.LTreeField(triggers=django_ltree_field.constants.LTreeTrigger['PROTECT'], unique=True)),
            ],
            options={
                'ordering': ['path'],
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['path'], name='protected_node_path_idx')],
            },
        ),
        migrations.CreateModel(
            name='SimpleNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django_ltree_field.fields.LTreeField(triggers=django_ltree_field.constants.LTreeTrigger['CASCADE'], unique=True)),
            ],
            options={
                'ordering': ['path'],
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['path'], name='simple_node_path_idx', opclasses=('gist_ltree_ops(siglen=100)',))],
            },
        ),
    ]
