# Generated by Django 5.1 on 2024-09-28 22:20

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nullablenode',
            index=django.contrib.postgres.indexes.GistIndex(models.F('path'), name='nullable_node_path_idx'),
        ),
        migrations.AddIndex(
            model_name='simplenode',
            index=django.contrib.postgres.indexes.GistIndex(fields=['path'], name='simple_node_path_idx', opclasses=('gist_ltree_ops',)),
        ),
    ]
