# Generated by Django 5.1 on 2024-09-28 22:21

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_nullablenode_nullable_node_path_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='simplenode',
            name='simple_node_path_idx',
        ),
        migrations.AddIndex(
            model_name='simplenode',
            index=django.contrib.postgres.indexes.GistIndex(fields=['path'], name='simple_node_path_idx', opclasses=('gist_ltree_ops(siglen=100)',)),
        ),
    ]
