# Generated by Django 5.1 on 2024-10-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_autonode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoNode',
            new_name='IntegerNode',
        ),
    ]
