# Generated by Django 5.1 on 2025-04-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_autonode'),
    ]

    operations = [
        migrations.AddField(
            model_name='autonode',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
