# Generated by Django 5.1 on 2024-10-07 15:12

from django.db import migrations
from django_ltree_field import triggers as ltree_triggers


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0003_remove_simplenode_simple_node_path_idx_and_more"),
    ]

    operations = [
        ltree_triggers.LtreeDeleteCascade(
            "simplenode",
            "path",
        )
    ]
