# Generated by Django 5.1 on 2024-10-11 02:19

from django.db import migrations

import django_ltree_field.constants
import django_ltree_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0003_rename_autonode_integernode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integernode",
            name="path",
            field=django_ltree_field.fields.IntegerLTreeField(
                triggers=django_ltree_field.constants.LTreeTrigger["PROTECT"]
            ),
        ),
    ]
