# Generated by Django 5.1 on 2024-10-11 04:58

import django_ltree_field.constants
import django_ltree_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_integernode_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nullablenode',
            name='path',
            field=django_ltree_field.fields.LTreeField(null=True, triggers=django_ltree_field.constants.LTreeTrigger['CASCADE'], unique=True),
        ),
        migrations.AlterField(
            model_name='protectednode',
            name='path',
            field=django_ltree_field.fields.LTreeField(triggers=django_ltree_field.constants.LTreeTrigger['PROTECT'], unique=True),
        ),
        migrations.AlterField(
            model_name='simplenode',
            name='path',
            field=django_ltree_field.fields.LTreeField(triggers=django_ltree_field.constants.LTreeTrigger['CASCADE'], unique=True),
        ),
    ]
