# Generated by Django 5.1 on 2024-10-12 06:50

from django.db import migrations

import django_ltree_field.constants
import django_ltree_field.fields
import django_ltree_field.integer_paths


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0005_alter_nullablenode_path_alter_protectednode_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integernode",
            name="path",
            field=django_ltree_field.fields.IntegerLTreeField(
                codec=django_ltree_field.integer_paths.PaddedCodec(
                    [
                        "0",
                        "1",
                        "2",
                        "3",
                        "4",
                        "5",
                        "6",
                        "7",
                        "8",
                        "9",
                        "A",
                        "B",
                        "C",
                        "D",
                        "E",
                        "F",
                        "G",
                        "H",
                        "I",
                        "J",
                        "K",
                        "L",
                        "M",
                        "N",
                        "O",
                        "P",
                        "Q",
                        "R",
                        "S",
                        "T",
                        "U",
                        "V",
                        "W",
                        "X",
                        "Y",
                        "Z",
                        "_",
                        "a",
                        "b",
                        "c",
                        "d",
                        "e",
                        "f",
                        "g",
                        "h",
                        "i",
                        "j",
                        "k",
                        "l",
                        "m",
                        "n",
                        "o",
                        "p",
                        "q",
                        "r",
                        "s",
                        "t",
                        "u",
                        "v",
                        "w",
                        "x",
                        "y",
                        "z",
                    ],
                    length=5,
                ),
                triggers=django_ltree_field.constants.LTreeTrigger["PROTECT"],
            ),
        ),
    ]
